CREATE TABLE IF NOT EXISTS clientes (
  id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  fecha_nacimiento DATE,
  email TEXT,
  telefono TEXT
);

CREATE TABLE IF NOT EXISTS productos (
  id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  color TEXT NOT NULL,
  cantidad_disponible INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_disponible >= 0),
  cantidad_apartada INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_apartada >= 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0)
);

CREATE TABLE IF NOT EXISTS compras (
  id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  estado TEXT NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Realizado'))
);

CREATE TABLE IF NOT EXISTS compras_detalle (
  id_compra INTEGER NOT NULL REFERENCES compras(id_compra),
  id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
  PRIMARY KEY (id_compra, id_producto)
);

CREATE TABLE IF NOT EXISTS carrito_temp (
  id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente),
  id_producto INTEGER NOT NULL REFERENCES productos(id_producto),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  PRIMARY KEY (id_cliente, id_producto)
);

INSERT INTO clientes (nombre, fecha_nacimiento, email, telefono)
SELECT v.nombre, v.fecha_nacimiento::date, v.email, v.telefono
FROM (VALUES
 ('Carlos Ruiz','1990-02-15','carlos.ruiz@correo.com','3001234567'),
 ('Lucía Méndez','1985-07-22','lucia.mendez@correo.com','3007654321'),
 ('Jorge Silva','1998-11-03','jorge.silva@correo.com','3009988776')
) AS v(nombre, fecha_nacimiento, email, telefono)
WHERE NOT EXISTS (SELECT 1 FROM clientes);

INSERT INTO productos (nombre, descripcion, color, cantidad_disponible, cantidad_apartada, precio_unitario)
SELECT v.nombre, v.descripcion, v.color, v.disponible, v.apartada, v.precio
FROM (VALUES
 ('Marco Aviador','Marco metálico estilo aviador, liviano y resistente','Metálico',48,2,60.00),
 ('Marco Cat-Eye','Marco estilizado de línea alta, ideal para uso diario','Rojo',19,1,85.00),
 ('Marco Rectangular','Marco rectangular clásico en acetato','Negro',77,3,20.00),
 ('Marco Redondo','Marco redondo minimalista tipo retro','Verde',60,0,45.00),
 ('Marco Deportivo','Marco deportivo resistente a impactos','Azul',30,0,55.00),
 ('Marco Infantil','Marco liviano y flexible para niños','Verde',40,0,30.00)
) AS v(nombre, descripcion, color, disponible, apartada, precio)
WHERE NOT EXISTS (SELECT 1 FROM productos);

INSERT INTO compras (id_cliente, fecha, hora, estado)
SELECT v.id_cliente, v.fecha::date, v.hora::time, v.estado
FROM (VALUES
 (1,'2026-08-25','10:15:00','Pendiente'),
 (2,'2026-08-26','11:40:00','Pendiente'),
 (3,'2026-08-27','09:05:00','Realizado')
) AS v(id_cliente, fecha, hora, estado)
WHERE NOT EXISTS (SELECT 1 FROM compras);

INSERT INTO compras_detalle (id_compra, id_producto, cantidad, precio_unitario)
SELECT v.id_compra, v.id_producto, v.cantidad, v.precio
FROM (VALUES (1,1,2,60.00),(2,2,1,85.00),(3,3,3,20.00)) AS v(id_compra,id_producto,cantidad,precio)
WHERE NOT EXISTS (SELECT 1 FROM compras_detalle);
